### ISSUE TITLE
http://www.serverless.cn/ 相关问题

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/website#7]
0. www.serverless.cn 的 SSL 证书过期了.
1. www.serverless.cn 底部的 ICP 备案编号对应的备案域名是 www.serverlessfans.cn .
2. 请问 www.serverless.cn 跟 www.serverless-devs.com 是什么关系 ?  
3. 前者看起来已经荒废已久了, 是否考虑修改 DNS , 自动跳转到后者? ![image](https://user-images.githubusercontent.com/16363180/140612964-8f766418-48d1-42f9-905f-459f56d03b0d.png)
![image](https://user-images.githubusercontent.com/16363180/140613040-26be26e8-2973-4b97-94a4-a46a30c44855.png)

**Comment by heimanba** [comment]
http://www.serverless.cn, 不是我们的域名哈，和serverless-devs没有联系的
