### ISSUE TITLE
https://www.serverless-devs.com/zh-cn/docs/intro.html 无法访问

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/website#8]
![image](https://user-images.githubusercontent.com/16363180/141429555-f85c98d6-06d4-46e8-9291-5497a0c0c3bb.png)

复现步骤:

0. 访问 https://www.serverless-devs.com/zh-cn/cli/index.html
1. 滚动到底部
2. 点击 "文档" 中的 "概览"

**Comment by heimanba** [comment]
新文档这个连接已经不存在哈，现在这个repo是比较老的官网repo.新的已经放在这里哈https://github.com/Serverless-Devs/serverless-website

**Comment by DevDengChao** [comment]
> 现在这个repo是比较老的官网repo

建议在 Readme 中注明 / 把这个废弃的仓库设置成 Archive 状态 / 设为私有仓库.

![image](https://user-images.githubusercontent.com/16363180/162343983-c6bd7e10-f22d-4f0e-bf57-d1023916b896.png)

**Comment by heimanba** [comment]
好的好的，收到



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月8日(周五) 上午9:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Serverless-Devs/website] https://www.serverless-devs.com/zh-cn/docs/intro.html 无法访问 (Issue #8)




  
现在这个repo是比较老的官网repo
 建议在 Readme 中注明 / 把这个废弃的仓库设置成 Archive 状态 / 设为私有仓库.
