### ISSUE TITLE
http://short.devsapp.cn/cicd/github/action/practice 无法访问

### ISSUE THREAD

**Issue by DevDengChao** [Serverless-Devs/website#9]
https://github.com/Serverless-Devs/website/blob/master/blog/zh-cn/serverless-devs-ci-cd-github-action-usage.md 文章末尾中包含的链接无法访问.

> 🍉 Serverless Devs的官网是通过Serverless Devs部署的: http://short.devsapp.cn/cicd/github/action/practice 

点击上述链接后跳转到了 http://www.serverless-devs.com/blog/serverless-devs-static-website-and-cd , 然后出现了 OSS 常见的 NoSuchKey 错误.

**Comment by heimanba** [comment]
由于官网升级，原来文章连接失效。已经订正哈

**Comment by heimanba** [comment]
感谢指出，由于官网升级，有些链接失效。后续所有的资料会沉淀到新官网www.serverless-devs.com



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月7日(周四) 中午11:01
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Serverless-Devs/website] http://short.devsapp.cn/cicd/github/action/practice 无法访问 (Issue #9)




 
https://github.com/Serverless-Devs/website/blob/master/blog/zh-cn/serverless-devs-ci-cd-github-action-usage.md 文章末尾中包含的连接无法访问.
  
🍉 Serverless Devs的官网是通过Serverless Devs部署的: http://short.devsapp.cn/cicd/github/action/practice
  
点击上述链接后跳转到了 http://www.serverless-devs.com/blog/serverless-devs-static-website-and-cd , 然后出现了 OSS 常见的 NoSuchKey 错误.
